// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateKsuid() {
  return window['go']['app']['Application']['CreateKsuid']();
}

export function DefaultSizeMainWindow() {
  return window['go']['app']['Application']['DefaultSizeMainWindow']();
}

export function InitApp() {
  return window['go']['app']['Application']['InitApp']();
}

export function PushDataToReact() {
  return window['go']['app']['Application']['PushDataToReact']();
}

export function ResizeMainWindow(arg1, arg2) {
  return window['go']['app']['Application']['ResizeMainWindow'](arg1, arg2);
}

export function Startup(arg1, arg2) {
  return window['go']['app']['Application']['Startup'](arg1, arg2);
}
