// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateKsuid():Promise<string>;

export function DefaultSizeMainWindow():Promise<void>;

export function ResizeMainWindow(arg1:number,arg2:number):Promise<void>;
